language: clojure
dist: trusty
lein: lein
before_script:
  # - ./bin/ci/install_mongodb.sh
  # - mongod --version 3.2
  # - ./bin/ci/before_script.sh
script: lein do clean, javac, test
# script: lein midje
script: lein bikeshed
script: lein cljfmt check
# script: lein eastwood
script: lein kibit
script: lein cloverage --fail-threshold 40

jdk:
  - oraclejdk8
services:
  - mongodb
deploy:
  provider: heroku
  api_key: b57c0a89-6981-4472-bf27-b203442b1460
  app: aqueous-sierra-27664
