language: clojure
lein: lein2
before_script:
  # - ./bin/ci/install_mongodb.sh
  # - mongod --version 3.2
  # - ./bin/ci/before_script.sh
script: lein2 do clean, javac, test
# script: lein midje
script: lein cloverage --fail-threshold 45
jdk:
  - oraclejdk8
services:
  - mongodb
deploy:
  provider: heroku
  api_key: 30610b40-9e28-4767-a927-f3257b370ef0
  app: aqueous-sierra-27664
